language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-test.txt

script: py.test --cov=wordpress tests.py

after_success: codecov
